import { Job } from "@/types/job";

export const MOCK_JOBS: Job[] = [
  {
    id: "job-1",
    title: "FullStack Engineer, AI Observability & Evals Platform",
    company: "LangChain",
    location: "San Francisco, CA (or Remote)",
    region: "us",
    matchScore: 94,
    matchedSkills: ["python", "typescript", "fastapi", "react", "llm", "rag", "docker"],
    missingSkills: ["clickhouse"],
    description:
      "We are looking for a FullStack Engineer to join our core team building LangSmith—the leading observability and evaluation platform for LLM applications. You will work across modern React/TypeScript frontends, high-performance Python/FastAPI backends, and distributed streaming systems.",
    url: "https://boards.greenhouse.io/langchain",
    postedAt: "2 days ago",
    ats: "greenhouse",
  },
  {
    id: "job-2",
    title: "AI/ML Engineer - Platform & Tooling",
    company: "Brillio",
    location: "Bangalore, Karnataka, India",
    region: "india",
    matchScore: 91,
    matchedSkills: ["python", "pytorch", "fastapi", "docker", "mlops", "git"],
    missingSkills: ["kubernetes", "airflow"],
    description:
      "Join our enterprise AI engineering team building production-ready generative AI platforms and agentic pipelines. Responsibilities include building scalable model inference APIs, fine-tuning open models, and implementing vector search systems for global clients.",
    url: "https://jobs.lever.co/brillio-2",
    postedAt: "3 days ago",
    ats: "lever",
  },
  {
    id: "job-3",
    title: "MTS - Performance & Systems Engineering",
    company: "Everpure",
    location: "Bangalore, Karnataka, India",
    region: "india",
    matchScore: 88,
    matchedSkills: ["python", "c++", "postgresql", "redis", "linux", "testing"],
    missingSkills: ["rust"],
    description:
      "Everpure is seeking a Member of Technical Staff to design low-latency distributed systems and data pipelines. You will optimize system bottlenecks, profile memory usage, and build core backend infrastructure.",
    url: "https://api.ashbyhq.com/everpure",
    postedAt: "1 day ago",
    ats: "ashby",
  },
  {
    id: "job-4",
    title: "Forward Deployed Engineer",
    company: "Cursor (Anysphere)",
    location: "San Francisco, CA / Remote",
    region: "remote",
    matchScore: 86,
    matchedSkills: ["typescript", "react", "nextjs", "python", "api", "git"],
    missingSkills: ["electron"],
    description:
      "As a Forward Deployed Engineer at Cursor, you will work closely with engineering teams at high-growth companies to integrate AI-assisted developer workflows and build mission-critical developer tools.",
    url: "https://jobs.ashbyhq.com/cursor",
    postedAt: "4 days ago",
    ats: "ashby",
  },
  {
    id: "job-5",
    title: "Software Engineer (Frontend Systems)",
    company: "Linear",
    location: "Remote (Global)",
    region: "remote",
    matchScore: 84,
    matchedSkills: ["typescript", "react", "tailwind", "websockets"],
    missingSkills: ["indexeddb"],
    description:
      "Linear is looking for a thoughtful frontend engineer to craft fast, fluid user experiences. You will contribute to our real-time synchronization engine, keyboard navigation architecture, and minimalist design systems.",
    url: "https://jobs.lever.co/linear",
    postedAt: "5 days ago",
    ats: "lever",
  },
  {
    id: "job-6",
    title: "Backend Software Engineer - Data Ingestion",
    company: "Palantir",
    location: "New York, NY",
    region: "us",
    matchScore: 81,
    matchedSkills: ["python", "postgresql", "docker", "rest", "system design"],
    missingSkills: ["spark", "kafka"],
    description:
      "Build high-throughput ingestion pipelines and core backend microservices for enterprise operations. Work alongside engineers deploying secure, large-scale distributed architectures.",
    url: "https://boards.greenhouse.io/palantir",
    postedAt: "Just now",
    ats: "greenhouse",
  },
];
